// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChunkInfo.proto

package GFS.Info;

public final class ChunkInfoProto {
  private ChunkInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChunkInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GFS.Info.ChunkInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string chunk_id = 1;</code>
     * @return The chunkId.
     */
    java.lang.String getChunkId();
    /**
     * <code>string chunk_id = 1;</code>
     * @return The bytes for chunkId.
     */
    com.google.protobuf.ByteString
        getChunkIdBytes();

    /**
     * <code>int64 file_seq = 2;</code>
     * @return The fileSeq.
     */
    long getFileSeq();

    /**
     * <code>int64 chunk_size = 3;</code>
     * @return The chunkSize.
     */
    long getChunkSize();

    /**
     * <code>string hash = 4;</code>
     * @return The hash.
     */
    java.lang.String getHash();
    /**
     * <code>string hash = 4;</code>
     * @return The bytes for hash.
     */
    com.google.protobuf.ByteString
        getHashBytes();
  }
  /**
   * Protobuf type {@code GFS.Info.ChunkInfo}
   */
  public static final class ChunkInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GFS.Info.ChunkInfo)
      ChunkInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChunkInfo.newBuilder() to construct.
    private ChunkInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChunkInfo() {
      chunkId_ = "";
      hash_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChunkInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GFS.Info.ChunkInfoProto.internal_static_GFS_Info_ChunkInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GFS.Info.ChunkInfoProto.internal_static_GFS_Info_ChunkInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GFS.Info.ChunkInfoProto.ChunkInfo.class, GFS.Info.ChunkInfoProto.ChunkInfo.Builder.class);
    }

    public static final int CHUNK_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object chunkId_ = "";
    /**
     * <code>string chunk_id = 1;</code>
     * @return The chunkId.
     */
    @java.lang.Override
    public java.lang.String getChunkId() {
      java.lang.Object ref = chunkId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chunkId_ = s;
        return s;
      }
    }
    /**
     * <code>string chunk_id = 1;</code>
     * @return The bytes for chunkId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChunkIdBytes() {
      java.lang.Object ref = chunkId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chunkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_SEQ_FIELD_NUMBER = 2;
    private long fileSeq_ = 0L;
    /**
     * <code>int64 file_seq = 2;</code>
     * @return The fileSeq.
     */
    @java.lang.Override
    public long getFileSeq() {
      return fileSeq_;
    }

    public static final int CHUNK_SIZE_FIELD_NUMBER = 3;
    private long chunkSize_ = 0L;
    /**
     * <code>int64 chunk_size = 3;</code>
     * @return The chunkSize.
     */
    @java.lang.Override
    public long getChunkSize() {
      return chunkSize_;
    }

    public static final int HASH_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hash_ = "";
    /**
     * <code>string hash = 4;</code>
     * @return The hash.
     */
    @java.lang.Override
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      }
    }
    /**
     * <code>string hash = 4;</code>
     * @return The bytes for hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chunkId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chunkId_);
      }
      if (fileSeq_ != 0L) {
        output.writeInt64(2, fileSeq_);
      }
      if (chunkSize_ != 0L) {
        output.writeInt64(3, chunkSize_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hash_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hash_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chunkId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chunkId_);
      }
      if (fileSeq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fileSeq_);
      }
      if (chunkSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, chunkSize_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hash_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hash_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GFS.Info.ChunkInfoProto.ChunkInfo)) {
        return super.equals(obj);
      }
      GFS.Info.ChunkInfoProto.ChunkInfo other = (GFS.Info.ChunkInfoProto.ChunkInfo) obj;

      if (!getChunkId()
          .equals(other.getChunkId())) return false;
      if (getFileSeq()
          != other.getFileSeq()) return false;
      if (getChunkSize()
          != other.getChunkSize()) return false;
      if (!getHash()
          .equals(other.getHash())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHUNK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId().hashCode();
      hash = (37 * hash) + FILE_SEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSeq());
      hash = (37 * hash) + CHUNK_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChunkSize());
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GFS.Info.ChunkInfoProto.ChunkInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GFS.Info.ChunkInfoProto.ChunkInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GFS.Info.ChunkInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GFS.Info.ChunkInfo)
        GFS.Info.ChunkInfoProto.ChunkInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GFS.Info.ChunkInfoProto.internal_static_GFS_Info_ChunkInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GFS.Info.ChunkInfoProto.internal_static_GFS_Info_ChunkInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GFS.Info.ChunkInfoProto.ChunkInfo.class, GFS.Info.ChunkInfoProto.ChunkInfo.Builder.class);
      }

      // Construct using GFS.Info.ChunkInfoProto.ChunkInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        chunkId_ = "";
        fileSeq_ = 0L;
        chunkSize_ = 0L;
        hash_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GFS.Info.ChunkInfoProto.internal_static_GFS_Info_ChunkInfo_descriptor;
      }

      @java.lang.Override
      public GFS.Info.ChunkInfoProto.ChunkInfo getDefaultInstanceForType() {
        return GFS.Info.ChunkInfoProto.ChunkInfo.getDefaultInstance();
      }

      @java.lang.Override
      public GFS.Info.ChunkInfoProto.ChunkInfo build() {
        GFS.Info.ChunkInfoProto.ChunkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GFS.Info.ChunkInfoProto.ChunkInfo buildPartial() {
        GFS.Info.ChunkInfoProto.ChunkInfo result = new GFS.Info.ChunkInfoProto.ChunkInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(GFS.Info.ChunkInfoProto.ChunkInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.chunkId_ = chunkId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fileSeq_ = fileSeq_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.chunkSize_ = chunkSize_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.hash_ = hash_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GFS.Info.ChunkInfoProto.ChunkInfo) {
          return mergeFrom((GFS.Info.ChunkInfoProto.ChunkInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GFS.Info.ChunkInfoProto.ChunkInfo other) {
        if (other == GFS.Info.ChunkInfoProto.ChunkInfo.getDefaultInstance()) return this;
        if (!other.getChunkId().isEmpty()) {
          chunkId_ = other.chunkId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getFileSeq() != 0L) {
          setFileSeq(other.getFileSeq());
        }
        if (other.getChunkSize() != 0L) {
          setChunkSize(other.getChunkSize());
        }
        if (!other.getHash().isEmpty()) {
          hash_ = other.hash_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                chunkId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                fileSeq_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                chunkSize_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                hash_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object chunkId_ = "";
      /**
       * <code>string chunk_id = 1;</code>
       * @return The chunkId.
       */
      public java.lang.String getChunkId() {
        java.lang.Object ref = chunkId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chunkId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chunk_id = 1;</code>
       * @return The bytes for chunkId.
       */
      public com.google.protobuf.ByteString
          getChunkIdBytes() {
        java.lang.Object ref = chunkId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chunkId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chunk_id = 1;</code>
       * @param value The chunkId to set.
       * @return This builder for chaining.
       */
      public Builder setChunkId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        chunkId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string chunk_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkId() {
        chunkId_ = getDefaultInstance().getChunkId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string chunk_id = 1;</code>
       * @param value The bytes for chunkId to set.
       * @return This builder for chaining.
       */
      public Builder setChunkIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        chunkId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long fileSeq_ ;
      /**
       * <code>int64 file_seq = 2;</code>
       * @return The fileSeq.
       */
      @java.lang.Override
      public long getFileSeq() {
        return fileSeq_;
      }
      /**
       * <code>int64 file_seq = 2;</code>
       * @param value The fileSeq to set.
       * @return This builder for chaining.
       */
      public Builder setFileSeq(long value) {

        fileSeq_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 file_seq = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSeq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileSeq_ = 0L;
        onChanged();
        return this;
      }

      private long chunkSize_ ;
      /**
       * <code>int64 chunk_size = 3;</code>
       * @return The chunkSize.
       */
      @java.lang.Override
      public long getChunkSize() {
        return chunkSize_;
      }
      /**
       * <code>int64 chunk_size = 3;</code>
       * @param value The chunkSize to set.
       * @return This builder for chaining.
       */
      public Builder setChunkSize(long value) {

        chunkSize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 chunk_size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chunkSize_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object hash_ = "";
      /**
       * <code>string hash = 4;</code>
       * @return The hash.
       */
      public java.lang.String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hash = 4;</code>
       * @return The bytes for hash.
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        java.lang.Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hash = 4;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        hash_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        hash_ = getDefaultInstance().getHash();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 4;</code>
       * @param value The bytes for hash to set.
       * @return This builder for chaining.
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        hash_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GFS.Info.ChunkInfo)
    }

    // @@protoc_insertion_point(class_scope:GFS.Info.ChunkInfo)
    private static final GFS.Info.ChunkInfoProto.ChunkInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GFS.Info.ChunkInfoProto.ChunkInfo();
    }

    public static GFS.Info.ChunkInfoProto.ChunkInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChunkInfo>
        PARSER = new com.google.protobuf.AbstractParser<ChunkInfo>() {
      @java.lang.Override
      public ChunkInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChunkInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GFS.Info.ChunkInfoProto.ChunkInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GFS_Info_ChunkInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GFS_Info_ChunkInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ChunkInfo.proto\022\010GFS.Info\"Q\n\tChunkInfo" +
      "\022\020\n\010chunk_id\030\001 \001(\t\022\020\n\010file_seq\030\002 \001(\003\022\022\n\n" +
      "chunk_size\030\003 \001(\003\022\014\n\004hash\030\004 \001(\tB\032\n\010GFS.In" +
      "foB\016ChunkInfoProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GFS_Info_ChunkInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GFS_Info_ChunkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GFS_Info_ChunkInfo_descriptor,
        new java.lang.String[] { "ChunkId", "FileSeq", "ChunkSize", "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
