// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResultInfo.proto

package myrmi.info;

public final class ResultInfoProto {
  private ResultInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:myrmi.Info.ResultInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes result = 1;</code>
     * @return The result.
     */
    com.google.protobuf.ByteString getResult();

    /**
     * <code>bytes Exception = 2;</code>
     * @return The exception.
     */
    com.google.protobuf.ByteString getException();

    /**
     * <code>int32 status = 3;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>int32 object_key = 4;</code>
     * @return The objectKey.
     */
    int getObjectKey();
  }
  /**
   * Protobuf type {@code myrmi.Info.ResultInfo}
   */
  public static final class ResultInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:myrmi.Info.ResultInfo)
      ResultInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResultInfo.newBuilder() to construct.
    private ResultInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultInfo() {
      result_ = com.google.protobuf.ByteString.EMPTY;
      exception_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResultInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return myrmi.info.ResultInfoProto.internal_static_myrmi_Info_ResultInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return myrmi.info.ResultInfoProto.internal_static_myrmi_Info_ResultInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              myrmi.info.ResultInfoProto.ResultInfo.class, myrmi.info.ResultInfoProto.ResultInfo.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResult() {
      return result_;
    }

    public static final int EXCEPTION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString exception_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes Exception = 2;</code>
     * @return The exception.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getException() {
      return exception_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_ = 0;
    /**
     * <code>int32 status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int OBJECT_KEY_FIELD_NUMBER = 4;
    private int objectKey_ = 0;
    /**
     * <code>int32 object_key = 4;</code>
     * @return The objectKey.
     */
    @java.lang.Override
    public int getObjectKey() {
      return objectKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!result_.isEmpty()) {
        output.writeBytes(1, result_);
      }
      if (!exception_.isEmpty()) {
        output.writeBytes(2, exception_);
      }
      if (status_ != 0) {
        output.writeInt32(3, status_);
      }
      if (objectKey_ != 0) {
        output.writeInt32(4, objectKey_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!result_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, result_);
      }
      if (!exception_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, exception_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (objectKey_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, objectKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof myrmi.info.ResultInfoProto.ResultInfo)) {
        return super.equals(obj);
      }
      myrmi.info.ResultInfoProto.ResultInfo other = (myrmi.info.ResultInfoProto.ResultInfo) obj;

      if (!getResult()
          .equals(other.getResult())) return false;
      if (!getException()
          .equals(other.getException())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (getObjectKey()
          != other.getObjectKey()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
      hash = (53 * hash) + getException().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + OBJECT_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getObjectKey();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static myrmi.info.ResultInfoProto.ResultInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(myrmi.info.ResultInfoProto.ResultInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code myrmi.Info.ResultInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:myrmi.Info.ResultInfo)
        myrmi.info.ResultInfoProto.ResultInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return myrmi.info.ResultInfoProto.internal_static_myrmi_Info_ResultInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return myrmi.info.ResultInfoProto.internal_static_myrmi_Info_ResultInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                myrmi.info.ResultInfoProto.ResultInfo.class, myrmi.info.ResultInfoProto.ResultInfo.Builder.class);
      }

      // Construct using myrmi.Info.ResultInfoProto.ResultInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = com.google.protobuf.ByteString.EMPTY;
        exception_ = com.google.protobuf.ByteString.EMPTY;
        status_ = 0;
        objectKey_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return myrmi.info.ResultInfoProto.internal_static_myrmi_Info_ResultInfo_descriptor;
      }

      @java.lang.Override
      public myrmi.info.ResultInfoProto.ResultInfo getDefaultInstanceForType() {
        return myrmi.info.ResultInfoProto.ResultInfo.getDefaultInstance();
      }

      @java.lang.Override
      public myrmi.info.ResultInfoProto.ResultInfo build() {
        myrmi.info.ResultInfoProto.ResultInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public myrmi.info.ResultInfoProto.ResultInfo buildPartial() {
        myrmi.info.ResultInfoProto.ResultInfo result = new myrmi.info.ResultInfoProto.ResultInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(myrmi.info.ResultInfoProto.ResultInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.exception_ = exception_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.objectKey_ = objectKey_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof myrmi.info.ResultInfoProto.ResultInfo) {
          return mergeFrom((myrmi.info.ResultInfoProto.ResultInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(myrmi.info.ResultInfoProto.ResultInfo other) {
        if (other == myrmi.info.ResultInfoProto.ResultInfo.getDefaultInstance()) return this;
        if (other.getResult() != com.google.protobuf.ByteString.EMPTY) {
          setResult(other.getResult());
        }
        if (other.getException() != com.google.protobuf.ByteString.EMPTY) {
          setException(other.getException());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getObjectKey() != 0) {
          setObjectKey(other.getObjectKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                result_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                exception_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                objectKey_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getResult() {
        return result_;
      }
      /**
       * <code>bytes result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString exception_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Exception = 2;</code>
       * @return The exception.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getException() {
        return exception_;
      }
      /**
       * <code>bytes Exception = 2;</code>
       * @param value The exception to set.
       * @return This builder for chaining.
       */
      public Builder setException(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        exception_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Exception = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000002);
        exception_ = getDefaultInstance().getException();
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      private int objectKey_ ;
      /**
       * <code>int32 object_key = 4;</code>
       * @return The objectKey.
       */
      @java.lang.Override
      public int getObjectKey() {
        return objectKey_;
      }
      /**
       * <code>int32 object_key = 4;</code>
       * @param value The objectKey to set.
       * @return This builder for chaining.
       */
      public Builder setObjectKey(int value) {

        objectKey_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 object_key = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearObjectKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        objectKey_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:myrmi.Info.ResultInfo)
    }

    // @@protoc_insertion_point(class_scope:myrmi.Info.ResultInfo)
    private static final myrmi.info.ResultInfoProto.ResultInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new myrmi.info.ResultInfoProto.ResultInfo();
    }

    public static myrmi.info.ResultInfoProto.ResultInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResultInfo>
        PARSER = new com.google.protobuf.AbstractParser<ResultInfo>() {
      @java.lang.Override
      public ResultInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResultInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public myrmi.info.ResultInfoProto.ResultInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_myrmi_Info_ResultInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_myrmi_Info_ResultInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ResultInfo.proto\022\nmyrmi.Info\"S\n\nResult" +
      "Info\022\016\n\006result\030\001 \001(\014\022\021\n\tException\030\002 \001(\014\022" +
      "\016\n\006status\030\003 \001(\005\022\022\n\nobject_key\030\004 \001(\005B\035\n\nm" +
      "yrmi.InfoB\017ResultInfoProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_myrmi_Info_ResultInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_myrmi_Info_ResultInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_myrmi_Info_ResultInfo_descriptor,
        new java.lang.String[] { "Result", "Exception", "Status", "ObjectKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
